### ISSUE TITLE
Timestamp of violation

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/fullstop#105]
Currently violations look like this:

~~~
{
    "id": 1,
    "created": null,
    "createdBy": null,
    "version": 0,
    "lastModified": null,
    "lastModifiedBy": null,
    "eventId": "87924782487624-da63-535a-83c1-662554adf424",
    "accountId": "123456789",
    "region": "eu-central-1",
    "message": "Instances with ids: [\"i-11111111\"] was started with wrong images: [ami-22222222]",
    "violationObject": null,
    "comment": null,
    "checked": null
}
~~~

I suppose it would be helpful to know when a violation was detected by fullstop (also: sorting). Is this timestamp gonna be inside the `created` field?

**Comment by mrandi** [comment]
Yes, that is right. I was waiting for the oauth2 integration, in order to use the spring auditing to fill out the created (timestamp), createdBy (user/robot) and the same for the lastModifiedBy fields (how acknowledge the violation).

Fields name should be changed in order to stay conformed with our policy.
I will inform you when we are finished with with tickets.
