### ISSUE TITLE
Use lifecycle to get app id and app version id (more information as possible)

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#396]
### Expected behavior
Use lifecycle to get app id and app version id (more information as possible) if the instance is already down. This will help reading the violations.

### Step needed

- [ ]  change query for whitlisting rule
- [ ]  change provider

### Dependencies

- [ ]  whitelist old violation that depends on this information (example: odd)
-   evaluate if is possible to add in meta_info this missing information for old violations

**Comment by harti2006** [comment]
Actually, looking this data up in the "lifecycle" tables wouldn't be sufficient in each case. We have to make sure that application_id (and version_id) is always available (where possible), because a lot of white-listing rules depend on it.

We decided to make both properties available as fields, rather than just have it in a meta-data json object. 

Of course it will be necessary to populate the new fields in all plugins and jobs.
