### ISSUE TITLE
Relative redirection is considered as a violation

### ISSUE THREAD

**Issue by Nilegfx** [zalando-stups/fullstop#496]
I got this message 

```
Error: "Call to https://xxxxxxx.eu-central-1.elb.amazonaws.com:443 redirects (status 302) to location with unsafe protocol (/auth/zalando)"
```
### Expected behavior
relative redirections shouldn't consider as a violation

**Comment by harti2006** [comment]
@Nilegfx I thought about your case and I think it is ok to show a violation here, however the message is wrong:
When Fullstop requests an API with no OAuth header, it expects it to respond with a 401 "Unauthorized", instead of a redirect.
Of course there are cases where the redirect to a login page is intended. Then please set the "publicly_accessible" flag in Yourturn/Kio for your application. Fullstop will then consider the redirect as ok.

The misleading error message is fixed in #498
